"""
clean_for_retrain.py — remove exactly the artefacts invalidated by a change to
the model INPUT FEATURES, and nothing else.

    python clean_for_retrain.py          # dry run, lists what would go
    python clean_for_retrain.py --yes    # actually delete

WHY THIS IS NEEDED
------------------
EXOG_FEATURES went from 19 to 21 columns (Is_Bridge_Day, Days_To_Holiday).
Nothing in the caching layer hashes that list:

  * 05b's fingerprint() hashes the CSV size/mtime, the selection file, WINDOW,
    HORIZON, EPOCHS, SEED, BATCH_SIZE, PATIENCE and Z_BETA -- not the feature
    list. Left alone it would report "forecasts up to date" and skip retraining
    entirely, so the new features would silently never be used.
  * research_multihorizon's checkpoint keys on (substation, model) only, so a
    resumed sweep would mix 19-feature and 21-feature cells in one selection
    table.
  * Saved .keras models have Input(shape=(14, 19)) baked in, and the pickled
    MinMaxScalers were fitted on 19 columns. Feeding them 21 raises a shape
    error at best; there is no silent-wrong-answer path here, but they are dead
    weight either way.

WHAT IS DELIBERATELY KEPT
-------------------------
  * BPDB_Dhaka_City_Substations_Page3.csv  -- the raw record, never touched
  * everything else in data/               -- the 00-04 synthetic household
                                              dataset lives here and is
                                              expensive to regenerate
  * kg/                                    -- rebuilt by 08 after forecasting
  * global_model_selection.csv             -- RENAMED, not deleted, so the
                                              pre-change winner stays citable
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).parent
YES = "--yes" in sys.argv

# (path-or-glob, reason)
DELETE_GLOBS = [
    ("forecast_outputs/_multihorizon_partial*.csv", "Phase-1 checkpoint: 19-feature cells"),
    ("forecast_outputs/_horizon_skill_partial*.csv", "Phase-1 per-lead checkpoint"),
    ("forecast_outputs/horizon_skill_all*.csv", "per-lead table, append-only"),
    ("forecast_outputs/metrics_summary_multihorizon*.csv", "per-cell metrics"),
    ("forecast_outputs/best_model_per_substation_mh*.csv", "winner's per-substation metrics"),
    ("forecast_outputs/*.png", "all figures, regenerated by the sweep"),
    ("forecast_outputs/global_best_model.txt", "winner justification"),
    ("models/*.keras", "trained with Input(shape=(14, 19))"),
    ("models/*_scaler.pkl", "MinMaxScaler fitted on 19 columns"),
    ("data/05b_forecast_meta.json", "05b fingerprint — MUST go or 05b skips retraining"),
    ("data/05b_*_daily_forecast.csv", "stale 19-feature forecasts"),
    ("data/05c_*_horizon_skill.csv", "stale 19-feature skill curves"),
]
DELETE_DIRS = [
    ("forecast_outputs/mh_preds", "stored test predictions from 19-feature models"),
    ("__pycache__", "stale bytecode"),
]
RENAME = [
    ("forecast_outputs/global_model_selection.csv",
     "forecast_outputs/global_model_selection_PRE_BRIDGEDAY.csv",
     "keep the pre-feature-change winner for the before/after table"),
]
KEEP_NOTE = [
    "BPDB_Dhaka_City_Substations_Page3.csv  (raw record)",
    "data/  — everything except the 05b/05c files above, incl. the 00-04 synthetic dataset",
    "kg/    — rebuilt by 08_knowledge_graph.py afterwards",
    "data/processed_dataset.csv — harmless either way, load_and_clean rewrites it",
]


def main() -> None:
    planned: list[tuple[Path, str]] = []
    for pattern, why in DELETE_GLOBS:
        for p in sorted(ROOT.glob(pattern)):
            if p.is_file():
                planned.append((p, why))
    dirs = [(ROOT / d, why) for d, why in DELETE_DIRS if (ROOT / d).is_dir()]
    renames = [(ROOT / a, ROOT / b, why) for a, b, why in RENAME if (ROOT / a).exists()]

    mode = "DELETING" if YES else "DRY RUN — nothing will be touched"
    print("=" * 74)
    print(f"clean_for_retrain.py — {mode}")
    print(f"root: {ROOT.resolve()}")
    print("=" * 74)

    if renames:
        print("\nRENAME (kept, not deleted):")
        for src, dst, why in renames:
            print(f"  {src.relative_to(ROOT)}\n    -> {dst.name}   [{why}]")

    print(f"\nDELETE — {len(planned)} file(s):")
    if not planned:
        print("  (nothing found — already clean)")
    last = None
    for p, why in planned:
        if why != last:
            print(f"  [{why}]")
            last = why
        print(f"    {p.relative_to(ROOT)}")

    if dirs:
        print(f"\nDELETE — {len(dirs)} folder(s):")
        for d, why in dirs:
            n = sum(1 for _ in d.rglob("*") if _.is_file())
            print(f"    {d.relative_to(ROOT)}/  ({n} files)  [{why}]")

    print("\nKEPT (never touched by this script):")
    for k in KEEP_NOTE:
        print(f"    {k}")

    if not YES:
        print("\n" + "=" * 74)
        print("Dry run. Re-run with --yes to apply:  python clean_for_retrain.py --yes")
        return

    for src, dst, _ in renames:
        if dst.exists():
            print(f"\n! {dst.name} already exists — leaving {src.name} in place")
        else:
            src.rename(dst)
            print(f"\nrenamed {src.name} -> {dst.name}")
    for p, _ in planned:
        p.unlink()
    for d, _ in dirs:
        shutil.rmtree(d)

    print(f"\nDeleted {len(planned)} file(s) and {len(dirs)} folder(s).")
    print("\nNext:")
    print("  python Run_research.py               # Phase 1, 108 trainings")
    print("  python 05b_substation_forecast.py    # deploy the winner")
    print("  python 06_molp_optimizer.py")
    print("  python 08_knowledge_graph.py")


if __name__ == "__main__":
    main()