// GenTwin-SG knowledge graph loader
// Generated by 08_knowledge_graph.py. K = (V, E, lab, rho), Eq. (57).
//
// Place the nodes_*.csv and relationships.csv files in Neo4j's import folder,
// then run this file in Neo4j Browser or cypher-shell.
//
// Backward compatibility: :Household also carries :User and :Event also
// carries :DrEvent, and PoolEntity.chi is mirrored to gcs_score, so the
// earlier GraphRAG query pack still runs.


// ---- constraints and indexes ----
CREATE CONSTRAINT substation_id IF NOT EXISTS FOR (n:Substation) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT touwindow_id IF NOT EXISTS FOR (n:TouWindow) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT tieline_id IF NOT EXISTS FOR (n:TieLine) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT applianceclass_id IF NOT EXISTS FOR (n:ApplianceClass) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT archetype_id IF NOT EXISTS FOR (n:Archetype) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT tariffclass_id IF NOT EXISTS FOR (n:TariffClass) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT day_id IF NOT EXISTS FOR (n:Day) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT timeslot_id IF NOT EXISTS FOR (n:TimeSlot) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT household_id IF NOT EXISTS FOR (n:Household) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT meter_id IF NOT EXISTS FOR (n:Meter) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT appliance_id IF NOT EXISTS FOR (n:Appliance) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT forecast_id IF NOT EXISTS FOR (n:Forecast) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT optimizationrun_id IF NOT EXISTS FOR (n:OptimizationRun) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT surcharge_id IF NOT EXISTS FOR (n:Surcharge) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT decision_id IF NOT EXISTS FOR (n:Decision) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT loadprofile_id IF NOT EXISTS FOR (n:LoadProfile) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT draction_id IF NOT EXISTS FOR (n:DrAction) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT regime_id IF NOT EXISTS FOR (n:Regime) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT event_id IF NOT EXISTS FOR (n:Event) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT prioritypool_id IF NOT EXISTS FOR (n:PriorityPool) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT poolentity_id IF NOT EXISTS FOR (n:PoolEntity) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT participationsummary_id IF NOT EXISTS FOR (n:ParticipationSummary) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT billingperiod_id IF NOT EXISTS FOR (n:BillingPeriod) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT monthlybill_id IF NOT EXISTS FOR (n:MonthlyBill) REQUIRE n.id IS UNIQUE;
CREATE INDEX timeslot_slot_index IF NOT EXISTS FOR (n:TimeSlot) ON (n.slot_index);
CREATE INDEX timeslot_date IF NOT EXISTS FOR (n:TimeSlot) ON (n.date);
CREATE INDEX draction_date IF NOT EXISTS FOR (n:DrAction) ON (n.date);
CREATE INDEX draction_clock IF NOT EXISTS FOR (n:DrAction) ON (n.clock);
CREATE INDEX decision_var_type IF NOT EXISTS FOR (n:Decision) ON (n.var_type);
CREATE INDEX decision_clock IF NOT EXISTS FOR (n:Decision) ON (n.clock);
CREATE INDEX event_regime IF NOT EXISTS FOR (n:Event) ON (n.regime);
CREATE INDEX household_category IF NOT EXISTS FOR (n:Household) ON (n.category);
CREATE INDEX participationsummary_never_curtailed IF NOT EXISTS FOR (n:ParticipationSummary) ON (n.never_curtailed);

// ---- Substation (2) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Substation.csv' AS row
CALL { WITH row
  MERGE (n:Substation {id: row.id})
  SET n.b_max_kw = row.b_max_kw, n.c_producer_tk_per_kwh = row.c_producer_tk_per_kwh, n.code = row.code, n.coords_provisional = row.coords_provisional, n.e_max_kwh = row.e_max_kwh, n.eta_ch = row.eta_ch, n.eta_dis = row.eta_dis, n.feeder_voltage_kv = row.feeder_voltage_kv, n.g_max_kw = row.g_max_kw, n.latitude = row.latitude, n.longitude = row.longitude, n.name = row.name, n.p_max_kw = row.p_max_kw, n.reserve_kwh = row.reserve_kwh, n.s0_kwh = row.s0_kwh, n.t_pk_label = row.t_pk_label, n.t_pk_slots = row.t_pk_slots, n.upstream_kv = row.upstream_kv
} IN TRANSACTIONS OF 5000 ROWS;

// ---- TouWindow (2) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_TouWindow.csv' AS row
CALL { WITH row
  MERGE (n:TouWindow {id: row.id})
  SET n.is_replacement_tariff = row.is_replacement_tariff, n.mu_off = row.mu_off, n.mu_peak = row.mu_peak, n.mu_source = row.mu_source, n.slots = row.slots, n.substation = row.substation, n.window_label = row.window_label, n.window_source = row.window_source
} IN TRANSACTIONS OF 5000 ROWS;

// ---- TieLine (2) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_TieLine.csv' AS row
CALL { WITH row
  MERGE (n:TieLine {id: row.id})
  SET n.from = row.from, n.loss_fraction = row.loss_fraction, n.price_tk_per_kwh = row.price_tk_per_kwh, n.t_max_kw = row.t_max_kw, n.to = row.to
} IN TRANSACTIONS OF 5000 ROWS;

// ---- ApplianceClass (3) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_ApplianceClass.csv' AS row
CALL { WITH row
  MERGE (n:ApplianceClass {id: row.id})
  SET n.explanation_template = row.explanation_template, n.name = row.name, n.voll_tk_per_kwh = row.voll_tk_per_kwh
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Archetype (8) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Archetype.csv' AS row
CALL { WITH row
  MERGE (n:Archetype {id: row.id})
  SET n.category = row.category, n.description = row.description, n.name = row.name, n.tariff_class = row.tariff_class
} IN TRANSACTIONS OF 5000 ROWS;

// ---- TariffClass (4) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_TariffClass.csv' AS row
CALL { WITH row
  MERGE (n:TariffClass {id: row.id})
  SET n.code = row.code, n.demand_charge = row.demand_charge, n.flat_tk_per_kwh = row.flat_tk_per_kwh, n.has_tou = row.has_tou, n.name_en = row.name_en, n.off_peak = row.off_peak, n.peak = row.peak, n.source = row.source, n.voltage = row.voltage
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Day (14) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Day.csv' AS row
CALL { WITH row
  MERGE (n:Day {id: row.id})
  SET n.date = row.date, n.is_dispatch_day = row.is_dispatch_day
} IN TRANSACTIONS OF 5000 ROWS;

// ---- TimeSlot (144) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_TimeSlot.csv' AS row
CALL { WITH row
  MERGE (n:TimeSlot {id: row.id})
  SET n.clock = row.clock, n.date = row.date, n.delta_h = row.delta_h, n.slot_index = row.slot_index
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Household (800) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Household.csv' AS row
CALL { WITH row
  MERGE (n:Household:User {id: row.id})
  SET n.archetype = row.archetype, n.category = row.category, n.connected_load_kw = row.connected_load_kw, n.gamma_cu_h = row.gamma_cu_h, n.gamma_sh_h = row.gamma_sh_h, n.household_id = row.household_id, n.lambda_h = row.lambda_h, n.n_appliances = row.n_appliances, n.represents_population = row.represents_population, n.substation = row.substation, n.tariff_class = row.tariff_class, n.w_h = row.w_h, n.y_max_h = row.y_max_h
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Meter (800) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Meter.csv' AS row
CALL { WITH row
  MERGE (n:Meter {id: row.id})
  SET n.household_id = row.household_id, n.meter_id = row.meter_id, n.n_appliances = row.n_appliances, n.substation = row.substation
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Appliance (5416) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Appliance.csv' AS row
CALL { WITH row
  MERGE (n:Appliance {id: row.id})
  SET n.appliance_id = row.appliance_id, n.cls = row.cls, n.duty_cycle = row.duty_cycle, n.household_id = row.household_id, n.name = row.name, n.p_rat_kw = row.p_rat_kw, n.quantity = row.quantity, n.schedule = row.schedule, n.thermal_response = row.thermal_response
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Forecast (28) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Forecast.csv' AS row
CALL { WITH row
  MERGE (n:Forecast {id: row.id})
  SET n.date = row.date, n.deficit_kw = row.deficit_kw, n.holiday_type = row.holiday_type, n.horizon_k = row.horizon_k, n.in_dispatch_horizon = row.in_dispatch_horizon, n.kappa = row.kappa, n.model = row.model, n.p_hat_kw = row.p_hat_kw, n.p_max_kw = row.p_max_kw, n.p_ref_kw = row.p_ref_kw, n.p_str_kw = row.p_str_kw, n.p_tilde_kw = row.p_tilde_kw, n.reference_day = row.reference_day, n.s_stress = row.s_stress, n.sigma_kw = row.sigma_kw, n.sigma_method = row.sigma_method, n.substation = row.substation, n.uncertainty_margin_kw = row.uncertainty_margin_kw, n.weather_source = row.weather_source, n.z_beta = row.z_beta
} IN TRANSACTIONS OF 5000 ROWS;

// ---- OptimizationRun (3) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_OptimizationRun.csv' AS row
CALL { WITH row
  MERGE (n:OptimizationRun {id: row.id})
  SET n.date = row.date, n.delta_h = row.delta_h, n.formulation = row.formulation, n.max_c1_slack_kw = row.max_c1_slack_kw, n.n_c7_binding = row.n_c7_binding, n.objective_F_tk = row.objective_F_tk, n.qoe_min = row.qoe_min, n.slots_per_day = row.slots_per_day, n.solver = row.solver, n.theta1 = row.theta1, n.theta2 = row.theta2, n.theta3 = row.theta3
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Surcharge (6) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Surcharge.csv' AS row
CALL { WITH row
  MERGE (n:Surcharge {id: row.id})
  SET n.B_id_kwh = row.B_id_kwh, n.F_i_tk = row.F_i_tk, n.G_id_kwh = row.G_id_kwh, n.T_ijd_kwh = row.T_ijd_kwh, n.date = row.date, n.f_cost_tk = row.f_cost_tk, n.f_rel_tk = row.f_rel_tk, n.f_wel_tk = row.f_wel_tk, n.substation = row.substation, n.varpi_tk_per_kwh = row.varpi_tk_per_kwh
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Decision (2592) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Decision.csv' AS row
CALL { WITH row
  MERGE (n:Decision {id: row.id})
  SET n.clock = row.clock, n.date = row.date, n.equation = row.equation, n.slot_index = row.slot_index, n.substation = row.substation, n.unit = row.unit, n.value = row.value, n.var_type = row.var_type
} IN TRANSACTIONS OF 5000 ROWS;

// ---- LoadProfile (288) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_LoadProfile.csv' AS row
CALL { WITH row
  MERGE (n:LoadProfile {id: row.id})
  SET n.c1_slack_kw = row.c1_slack_kw, n.clock = row.clock, n.date = row.date, n.pi_tk_per_kwh = row.pi_tk_per_kwh, n.post_response_kw = row.post_response_kw, n.slot_index = row.slot_index, n.soc_kwh = row.soc_kwh, n.substation = row.substation
} IN TRANSACTIONS OF 5000 ROWS;

// ---- DrAction (28457) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_DrAction.csv' AS row
CALL { WITH row
  MERGE (n:DrAction {id: row.id})
  SET n.action = row.action, n.at_cap = row.at_cap, n.c7_binding = row.c7_binding, n.clock = row.clock, n.consumer_id = row.consumer_id, n.date = row.date, n.discomfort_tk_per_kwh = row.discomfort_tk_per_kwh, n.energy_kwh = row.energy_kwh, n.equation = row.equation, n.kappa = row.kappa, n.lambda_h = row.lambda_h, n.lambda_star = row.lambda_star, n.margin = row.margin, n.pi_i_t = row.pi_i_t, n.private_tk_per_kwh = row.private_tk_per_kwh, n.qoe_tk_per_kwh = row.qoe_tk_per_kwh, n.slot_index = row.slot_index, n.substation = row.substation, n.system_tk_per_kwh = row.system_tk_per_kwh, n.threshold_form = row.threshold_form, n.value = row.value, n.y_max_h = row.y_max_h
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Regime (6) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Regime.csv' AS row
CALL { WITH row
  MERGE (n:Regime {id: row.id})
  SET n.beta1 = row.beta1, n.computed_after_solve = row.computed_after_solve, n.date = row.date, n.equation = row.equation, n.r = row.r, n.regime_name = row.regime_name, n.s_stress = row.s_stress, n.substation = row.substation, n.trigger_capacity_deficit = row.trigger_capacity_deficit, n.trigger_reserve_shortfall = row.trigger_reserve_shortfall, n.trigger_transfer = row.trigger_transfer
} IN TRANSACTIONS OF 5000 ROWS;

// ---- Event (11) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_Event.csv' AS row
CALL { WITH row
  MERGE (n:Event:DrEvent {id: row.id})
  SET n.actual_peak_kw = row.actual_peak_kw, n.cost_impact_tk = row.cost_impact_tk, n.date = row.date, n.deficit_kw = row.deficit_kw, n.energy_curtailed_kwh = row.energy_curtailed_kwh, n.energy_reduction_kwh = row.energy_reduction_kwh, n.energy_shifted_kwh = row.energy_shifted_kwh, n.event_id = row.event_id, n.forecast_peak_kw = row.forecast_peak_kw, n.kappa = row.kappa, n.n_affected_consumers = row.n_affected_consumers, n.n_threshold_records = row.n_threshold_records, n.p_max_kw = row.p_max_kw, n.p_str_kw = row.p_str_kw, n.pi_max_tk_per_kwh = row.pi_max_tk_per_kwh, n.pi_min_tk_per_kwh = row.pi_min_tk_per_kwh, n.regime = row.regime, n.regime_name = row.regime_name, n.reserve_shortfall_kwh = row.reserve_shortfall_kwh, n.robust_peak_kw = row.robust_peak_kw, n.stress_indicator = row.stress_indicator, n.substation = row.substation, n.timestamp = row.timestamp, n.transfer_out_kwh = row.transfer_out_kwh, n.trigger = row.trigger, n.unserved_kwh = row.unserved_kwh
} IN TRANSACTIONS OF 5000 ROWS;

// ---- PriorityPool (9) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_PriorityPool.csv' AS row
CALL { WITH row
  MERGE (n:PriorityPool {id: row.id})
  SET n.W_P = row.W_P, n.alpha_P = row.alpha_P, n.chi_bar = row.chi_bar, n.chi_max = row.chi_max, n.chi_mean = row.chi_mean, n.chi_min = row.chi_min, n.cut_high = row.cut_high, n.cut_low = row.cut_low, n.date = row.date, n.degenerate = row.degenerate, n.equation = row.equation, n.n = row.n, n.pool = row.pool, n.rule = row.rule
} IN TRANSACTIONS OF 5000 ROWS;

// ---- PoolEntity (150) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_PoolEntity.csv' AS row
CALL { WITH row
  MERGE (n:PoolEntity {id: row.id})
  SET n.chi = row.chi, n.date = row.date, n.entity_id = row.entity_id, n.equation = row.equation, n.gcs_score = row.gcs_score, n.kind = row.kind, n.pool = row.pool, n.rank = row.rank, n.substation = row.substation
} IN TRANSACTIONS OF 5000 ROWS;

// ---- ParticipationSummary (2400) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_ParticipationSummary.csv' AS row
CALL { WITH row
  MERGE (n:ParticipationSummary {id: row.id})
  SET n.archetype = row.archetype, n.category = row.category, n.consumer_id = row.consumer_id, n.date = row.date, n.energy_curtailed_kwh = row.energy_curtailed_kwh, n.energy_shifted_kwh = row.energy_shifted_kwh, n.max_y = row.max_y, n.n_curtail_slots = row.n_curtail_slots, n.n_shift_slots = row.n_shift_slots, n.never_curtailed = row.never_curtailed, n.never_shifted = row.never_shifted, n.participated = row.participated, n.substation = row.substation, n.w_h = row.w_h
} IN TRANSACTIONS OF 5000 ROWS;

// ---- BillingPeriod (1) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_BillingPeriod.csv' AS row
CALL { WITH row
  MERGE (n:BillingPeriod {id: row.id})
  SET n.days = row.days, n.end = row.end, n.forecast_days = row.forecast_days, n.month_label = row.month_label, n.observed_days = row.observed_days, n.qoe_min = row.qoe_min, n.rho_tk_per_kwh = row.rho_tk_per_kwh, n.start = row.start, n.tariff_source = row.tariff_source
} IN TRANSACTIONS OF 5000 ROWS;

// ---- MonthlyBill (800) ----
LOAD CSV WITH HEADERS FROM 'file:///nodes_MonthlyBill.csv' AS row
CALL { WITH row
  MERGE (n:MonthlyBill {id: row.id})
  SET n.J1_after_tk = row.J1_after_tk, n.J1_before_tk = row.J1_before_tk, n.bill_after_tk = row.bill_after_tk, n.bill_before_tk = row.bill_before_tk, n.bill_saving_pct = row.bill_saving_pct, n.bill_saving_tk = row.bill_saving_tk, n.days = row.days, n.discomfort_cost_tk = row.discomfort_cost_tk, n.eff_rate_after = row.eff_rate_after, n.eff_rate_before = row.eff_rate_before, n.energy_after_kwh = row.energy_after_kwh, n.energy_before_kwh = row.energy_before_kwh, n.energy_curtailed_kwh = row.energy_curtailed_kwh, n.energy_saving_kwh = row.energy_saving_kwh, n.energy_shifted_kwh = row.energy_shifted_kwh, n.equation = row.equation, n.gained = row.gained, n.household_id = row.household_id, n.household_size = row.household_size, n.incentive_received_tk = row.incentive_received_tk, n.income_band = row.income_band, n.marginal_rate_tk_per_kwh = row.marginal_rate_tk_per_kwh, n.monthly_income_bdt = row.monthly_income_bdt, n.n_curtail_slots = row.n_curtail_slots, n.n_dr_events = row.n_dr_events, n.n_shift_slots = row.n_shift_slots, n.net_benefit_tk = row.net_benefit_tk, n.participated = row.participated, n.peak_after_kw = row.peak_after_kw, n.peak_before_kw = row.peak_before_kw, n.peak_reduction_pct = row.peak_reduction_pct, n.period_end = row.period_end, n.period_start = row.period_start, n.qoe = row.qoe, n.slab_after = row.slab_after, n.slab_before = row.slab_before, n.substation = row.substation, n.surcharge_tk = row.surcharge_tk, n.tariff_class = row.tariff_class, n.w_h = row.w_h
} IN TRANSACTIONS OF 5000 ROWS;

// ---- relationships ----
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AFFECTS' AND row.src_label = 'Event' AND row.dst_label = 'Household'
CALL { WITH row
  MATCH (a:Event {id: row.src}), (b:Household {id: row.dst})
  MERGE (a)-[:AFFECTS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'APPLIES_TO' AND row.src_label = 'Decision' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:Decision {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:APPLIES_TO]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'APPLIES_TO' AND row.src_label = 'Regime' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:Regime {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:APPLIES_TO]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_DAY' AND row.src_label = 'Forecast' AND row.dst_label = 'Day'
CALL { WITH row
  MATCH (a:Forecast {id: row.src}), (b:Day {id: row.dst})
  MERGE (a)-[:AT_DAY]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_DAY' AND row.src_label = 'OptimizationRun' AND row.dst_label = 'Day'
CALL { WITH row
  MATCH (a:OptimizationRun {id: row.src}), (b:Day {id: row.dst})
  MERGE (a)-[:AT_DAY]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_DAY' AND row.src_label = 'ParticipationSummary' AND row.dst_label = 'Day'
CALL { WITH row
  MATCH (a:ParticipationSummary {id: row.src}), (b:Day {id: row.dst})
  MERGE (a)-[:AT_DAY]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_DAY' AND row.src_label = 'TimeSlot' AND row.dst_label = 'Day'
CALL { WITH row
  MATCH (a:TimeSlot {id: row.src}), (b:Day {id: row.dst})
  MERGE (a)-[:AT_DAY]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_TIMESLOT' AND row.src_label = 'Decision' AND row.dst_label = 'TimeSlot'
CALL { WITH row
  MATCH (a:Decision {id: row.src}), (b:TimeSlot {id: row.dst})
  MERGE (a)-[:AT_TIMESLOT]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_TIMESLOT' AND row.src_label = 'DrAction' AND row.dst_label = 'TimeSlot'
CALL { WITH row
  MATCH (a:DrAction {id: row.src}), (b:TimeSlot {id: row.dst})
  MERGE (a)-[:AT_TIMESLOT]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'AT_TIMESLOT' AND row.src_label = 'LoadProfile' AND row.dst_label = 'TimeSlot'
CALL { WITH row
  MATCH (a:LoadProfile {id: row.src}), (b:TimeSlot {id: row.dst})
  MERGE (a)-[:AT_TIMESLOT]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'BELONGS_TO' AND row.src_label = 'Appliance' AND row.dst_label = 'ApplianceClass'
CALL { WITH row
  MATCH (a:Appliance {id: row.src}), (b:ApplianceClass {id: row.dst})
  MERGE (a)-[:BELONGS_TO]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'BILLED' AND row.src_label = 'Household' AND row.dst_label = 'MonthlyBill'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:MonthlyBill {id: row.dst})
  MERGE (a)-[:BILLED]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'BILLED_UNDER' AND row.src_label = 'MonthlyBill' AND row.dst_label = 'BillingPeriod'
CALL { WITH row
  MATCH (a:MonthlyBill {id: row.src}), (b:BillingPeriod {id: row.dst})
  MERGE (a)-[:BILLED_UNDER]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'CAUSES' AND row.src_label = 'Event' AND row.dst_label = 'DrAction'
CALL { WITH row
  MATCH (a:Event {id: row.src}), (b:DrAction {id: row.dst})
  MERGE (a)-[:CAUSES]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'COMPUTED_FROM' AND row.src_label = 'Event' AND row.dst_label = 'OptimizationRun'
CALL { WITH row
  MATCH (a:Event {id: row.src}), (b:OptimizationRun {id: row.dst})
  MERGE (a)-[:COMPUTED_FROM]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'COMPUTED_FROM' AND row.src_label = 'Regime' AND row.dst_label = 'Forecast'
CALL { WITH row
  MATCH (a:Regime {id: row.src}), (b:Forecast {id: row.dst})
  MERGE (a)-[:COMPUTED_FROM]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'COMPUTED_FROM' AND row.src_label = 'Regime' AND row.dst_label = 'OptimizationRun'
CALL { WITH row
  MATCH (a:Regime {id: row.src}), (b:OptimizationRun {id: row.dst})
  MERGE (a)-[:COMPUTED_FROM]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'CONNECTS' AND row.src_label = 'Substation' AND row.dst_label = 'TieLine'
CALL { WITH row
  MATCH (a:Substation {id: row.src}), (b:TieLine {id: row.dst})
  MERGE (a)-[:CONNECTS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'CONNECTS' AND row.src_label = 'TieLine' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:TieLine {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:CONNECTS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'CONTAINS' AND row.src_label = 'PriorityPool' AND row.dst_label = 'PoolEntity'
CALL { WITH row
  MATCH (a:PriorityPool {id: row.src}), (b:PoolEntity {id: row.dst})
  MERGE (a)-[:CONTAINS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'COVERS' AND row.src_label = 'BillingPeriod' AND row.dst_label = 'Day'
CALL { WITH row
  MATCH (a:BillingPeriod {id: row.src}), (b:Day {id: row.dst})
  MERGE (a)-[:COVERS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'FEEDS_FROM' AND row.src_label = 'Meter' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:Meter {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:FEEDS_FROM]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'HAS_APPLIANCE' AND row.src_label = 'Household' AND row.dst_label = 'Appliance'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:Appliance {id: row.dst})
  MERGE (a)-[:HAS_APPLIANCE]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'HAS_EVENT' AND row.src_label = 'Substation' AND row.dst_label = 'Event'
CALL { WITH row
  MATCH (a:Substation {id: row.src}), (b:Event {id: row.dst})
  MERGE (a)-[:HAS_EVENT]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'HAS_HOUSEHOLD' AND row.src_label = 'Substation' AND row.dst_label = 'Household'
CALL { WITH row
  MATCH (a:Substation {id: row.src}), (b:Household {id: row.dst})
  MERGE (a)-[:HAS_HOUSEHOLD]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'HAS_METER' AND row.src_label = 'Household' AND row.dst_label = 'Meter'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:Meter {id: row.dst})
  MERGE (a)-[:HAS_METER]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'HAS_PROFILE' AND row.src_label = 'Substation' AND row.dst_label = 'LoadProfile'
CALL { WITH row
  MATCH (a:Substation {id: row.src}), (b:LoadProfile {id: row.dst})
  MERGE (a)-[:HAS_PROFILE]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'HAS_TOU_WINDOW' AND row.src_label = 'Substation' AND row.dst_label = 'TouWindow'
CALL { WITH row
  MATCH (a:Substation {id: row.src}), (b:TouWindow {id: row.dst})
  MERGE (a)-[:HAS_TOU_WINDOW]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'IN_ARCHETYPE' AND row.src_label = 'Household' AND row.dst_label = 'Archetype'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:Archetype {id: row.dst})
  MERGE (a)-[:IN_ARCHETYPE]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'LOCATED_AT' AND row.src_label = 'Household' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:LOCATED_AT]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'PARTICIPATED_IN' AND row.src_label = 'Household' AND row.dst_label = 'Event'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:Event {id: row.dst})
  MERGE (a)-[:PARTICIPATED_IN]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'PASSED_THROUGH' AND row.src_label = 'Substation' AND row.dst_label = 'Surcharge'
CALL { WITH row
  MATCH (a:Substation {id: row.src}), (b:Surcharge {id: row.dst})
  MERGE (a)-[:PASSED_THROUGH]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'PERFORMED' AND row.src_label = 'Household' AND row.dst_label = 'DrAction'
CALL { WITH row
  MATCH (a:Household {id: row.src}), (b:DrAction {id: row.dst})
  MERGE (a)-[:PERFORMED]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'PREDICTS' AND row.src_label = 'Forecast' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:Forecast {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:PREDICTS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'PRODUCED' AND row.src_label = 'OptimizationRun' AND row.dst_label = 'Decision'
CALL { WITH row
  MATCH (a:OptimizationRun {id: row.src}), (b:Decision {id: row.dst})
  MERGE (a)-[:PRODUCED]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'REDUCES' AND row.src_label = 'DrAction' AND row.dst_label = 'LoadProfile'
CALL { WITH row
  MATCH (a:DrAction {id: row.src}), (b:LoadProfile {id: row.dst})
  MERGE (a)-[:REDUCES]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'REGISTERS' AND row.src_label = 'Meter' AND row.dst_label = 'Appliance'
CALL { WITH row
  MATCH (a:Meter {id: row.src}), (b:Appliance {id: row.dst})
  MERGE (a)-[:REGISTERS]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'SOLVED_FOR' AND row.src_label = 'OptimizationRun' AND row.dst_label = 'Substation'
CALL { WITH row
  MATCH (a:OptimizationRun {id: row.src}), (b:Substation {id: row.dst})
  MERGE (a)-[:SOLVED_FOR]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'SUBJECT_TO' AND row.src_label = 'Archetype' AND row.dst_label = 'TariffClass'
CALL { WITH row
  MATCH (a:Archetype {id: row.src}), (b:TariffClass {id: row.dst})
  MERGE (a)-[:SUBJECT_TO]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'SUBJECT_TO' AND row.src_label = 'MonthlyBill' AND row.dst_label = 'TariffClass'
CALL { WITH row
  MATCH (a:MonthlyBill {id: row.src}), (b:TariffClass {id: row.dst})
  MERGE (a)-[:SUBJECT_TO]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'SUMMARISES' AND row.src_label = 'ParticipationSummary' AND row.dst_label = 'Household'
CALL { WITH row
  MATCH (a:ParticipationSummary {id: row.src}), (b:Household {id: row.dst})
  MERGE (a)-[:SUMMARISES]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'TRIGGERED_BY' AND row.src_label = 'Event' AND row.dst_label = 'Forecast'
CALL { WITH row
  MATCH (a:Event {id: row.src}), (b:Forecast {id: row.dst})
  MERGE (a)-[:TRIGGERED_BY]->(b)
} IN TRANSACTIONS OF 10000 ROWS;
LOAD CSV WITH HEADERS FROM 'file:///relationships.csv' AS row
WITH row WHERE row.type = 'UNDER_REGIME' AND row.src_label = 'Event' AND row.dst_label = 'Regime'
CALL { WITH row
  MATCH (a:Event {id: row.src}), (b:Regime {id: row.dst})
  MERGE (a)-[:UNDER_REGIME]->(b)
} IN TRANSACTIONS OF 10000 ROWS;